# SITE CONFIGURATION
baseurl: 
url: jangkunblog.com

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: 장군블로그
  favicon: favicon.ico
  description: 진심을 담은 마크업! 그 마음이 웹 접근성을 향상시킵니다.
  og-image: jangkunblog.png

 # Scripts
  google_analytics: UA-7379986-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: jangkunblog
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "page/:num"

#category
#category_path: 
#category_layout: 

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge


sass:
  sass_dir: _sass
  style: :compressed
plugins: 
  - jekyll-paginate
  
#  - jekyll-category-pages
# theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock

image:
  src: '/image.jpg'
  height: 
  width: 1366
  type: /png

# https://gist.github.com/codetheorist/98eaa139379f252de8ad29499aeae057
facebook:
  app_id: '260037468013892'
  pixel_id: '363394284468950'